### ISSUE TITLE
Feature Request: Create playlist from wantlist

### ISSUE THREAD

**Issue by MattyBalaam** [lim93/DiscogsToSpotify#1]
As a moderately heavy Discogs user, the ability to create a playlist from a Discogs wantlist would be a very welcome feature.

**Comment by lim93** [comment]
Hi @MattyBalaam!
The feature is now live on [discogstospotify.com](discogstospotify.com). I made some changes to the button layout and playlist names, but your technical implementation worked just fine. 
Thank you again for your contribution!
